### ISSUE TITLE
GetSerial Data Loadcell:       OSError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by Jan-WillemD** [Jan-WillemD/Monitoring#4]
Sonar is detecting plastic: 56 cm
Plastic detected! Starting Extraction
Maxbotix Ultrasonic sensor: Big bag volume: 89 cm
Traceback (most recent call last):
  File "Mock-up.py", line 98, in <module>
    weight, temp =getSerialData(LoadCellPort,2,2)
  File "Mock-up.py", line 48, in getSerialData
    SonarData = ser.readline()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 453, in re                          ad
    buf = os.read(self.fd, size-len(read))
OSError: [Errno 11] Resource temporarily unavailable

**Comment by Jan-WillemD** [comment]
flush serial data en éen serial connection
